### ISSUE TITLE
Incorrect behavior when enumerating models 

### ISSUE THREAD

**Issue by vale1410** [vale1410/bule#60] opened 2023-06-12 22:12 UTC
Call the following program with `--solve --models 0` does not iterate through all models, but stops with the first one and does not continue: 

```
#ground dim[1..4]. 
#ground ex[x], ex[y]. 
ex[E],  dim[I] :: #exists[0] v(E,I).   
dim[I] :: ~v(x,I) | ~v(y,I). 
```

**Comment by AbdallahS** [comment] 2023-06-13 01:02
Yeah, it's the usual issue with the embedded qbf solver that is buggy. Duplicate of issue #38 . You can run with '--solve --models 0 --solver minisat' or with '--solve --models 0 --solver "depqbf --no-dynamic-nenofex --qdo"' and it should work.

**Closed by AbdallahS** 2023-06-13 01:02 UTC
