### ISSUE TITLE
Syntax in bule ground for variable declaration 

### ISSUE THREAD

**Issue by vale1410** [vale1410/bule#41] opened 2022-02-26 18:36 UTC
The bule syntax for version 4 does not have `?` anymore. 

following bule program 
```
#exists[0] v(1).
```
with running bule on  it gives: 

```
#exists[0] :: v(1)?
```

should not return with question mark.

**Comment by AbdallahS** [comment] 2022-02-26 18:54
Is that a duplicate of #37 ? I thought it was fixed a few days ago.

**Closed** 2022-02-26 19:26 UTC
